# With this file, another toolchain to the currently selected one will be used, when you execute `cargo build`.
# https://rust-lang.github.io/rustup/overrides.html

[toolchain]
# equals to Rust nightly 1.55 as of the release day 2021-06-17
channel = "nightly-2021-06-17"
components = [ "rust-src", "rust-std", "rustc", "cargo" ]
