# With this file, another toolchain to the currently selected one will be used, when you execute `cargo build`.
# https://rust-lang.github.io/rustup/overrides.html

[toolchain]
# Rust nightly 1.65
channel = "nightly-2022-08-22"
components = [ "rust-src", "rust-std", "rustc", "cargo", "clippy", "rustfmt" ]
targets = [ "x86_64-unknown-none" ]
