[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
# https://github.com/rust-lang/rust/blob/1.62.0/compiler/rustc_target/src/spec/x86_64_unknown_none.rs
target = "x86_64-unknown-none"
rustflags = [
    "-C", "link-arg=-Tlink.ld"
]