# With this file, another toolchain to the currently selected one will be used, when you execute `cargo build`.
# https://rust-lang.github.io/rustup/overrides.html

[toolchain]
# Rust nightly 1.64
channel = "nightly-2022-06-30"
components = [ "rust-src", "rust-std", "rustc", "cargo" ]
# currently still without effect as there is no precompiled libcore for thie target
targets = [ "x86_64-unknown-none" ]